app:
  build: .
  env_file: .env
  environment:
    RAILS_ENV: production
  links:
    - db
  ports:
    - "3000:3000"

db:
  image: postgres:9.4.5
  volumes:
    - maid-in-sheffield-postgres:/var/lib/postgresql/data
