default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development-mis

test:
  <<: *default
  database: db/test-mis

production:
  <<: *default
  database: db/production-mis