default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  timeout: 5000
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: db/development-mis

test:
  <<: *default
  database: db/test-mis

production:
  <<: *default
  database: db/production-mis
