# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551d25fcc42bed50d4e20f68857ec52deb68884623e045f37dd3c06210f91e1e67be76d7725466d5deccc96e35e6d6ba80eb975575a35137226d42f8a1bb5be5

test:
  secret_key_base: 561e441cb168e381420dbeff118ef581641068f0752113ba20971184b2dbe9c8959944aee209fe1a9c284ab74233d406635c0652cceddc667a9e0d253e1767d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
